server:
  port: 8088
spring:
  profiles:
    active: test
  application:
    name: trade-security
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yml